{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ruby-helm.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
