name: ruby-ci

on:
  push:
    branches:
      - 'main'

env:
  COMMIT_SHA: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set COMMIT_SHA_SHORT
        id: commit_sha
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: h04x00/ruby-http:${{ steps.commit_sha.outputs.sha }}
